### ISSUE TITLE
Deprecated usage of S_IREAD and S_IWRITE

### ISSUE THREAD

**Issue by edelkas** [bitbank2/giflib-turbo#4]
For anyone having issues with undeclared constants `S_IREAD` and `S_IWRITE`, simply swap them in the `gif_lib.c` code by `S_IRUSR` and `S_IWUSR`, respectively, and that ought to solve it.

Not sure if there's any particular reason why they're being used here. The [glibc docs](https://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html) suggest they're only there for obsolete compatibility with BSD systems.

**Comment by bitbank2** [comment]
Can you please create a PR which uses #ifdef to redefine these for compatibility?

**Comment by edelkas** [comment]
Sure thing, done.
