### ISSUE TITLE
Can I decode row by row to downscaling images and save memory for big image.

### ISSUE THREAD

**Issue by jannson** [bitbank2/giflib-turbo#6]
Something like this issue: https://stackoverflow.com/questions/28154758/downscaling-images-when-decoding-with-libpng

I want to scale big gif image and save memory, is there a method to decode gif row by row, not reading the whole image to memory.

**Comment by bitbank2** [comment]
This library was designed for speed first, not to save memory. It uses the current frame as the dictionary, so you need to have a buffer of frame size (1 byte per pixel). It is possible to use my other GIF library (AnimatedGIF) and only keep the dictionary (24K) + 1 line of image. This can produce correct output if you don't have certain restore or palette operations.
